"""
PDF export service.

Generates a clean, professional PDF from lecture notes.
Uses reportlab for PDF creation.
"""

import io
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.units import mm, cm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether,
)

from app.database import get_lecture as db_get_lecture


# ── Quiet Study Brand Colors ──
PURPLE = HexColor("#9333EA")        # purple-600
DARK_TEXT = HexColor("#1a1815")     # primary dark
LIGHT_GRAY = HexColor("#8a7f6f")   # secondary text
MEDIUM_GRAY = HexColor("#b5ad9e")  # muted text
WHITE = HexColor("#FFFFFF")
CREAM = HexColor("#F7F4EE")        # background
PAPER = HexColor("#FDFCF9")        # card background
GOLD_BORDER = HexColor("#D9B982")  # accent border


def _get_styles():
    """Create custom styles for the Lectly PDF."""
    styles = getSampleStyleSheet()

    # Title
    styles.add(ParagraphStyle(
        name="LectlyTitle",
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=28,
        textColor=DARK_TEXT,
        spaceAfter=6,
    ))

    # Subtitle / summary
    styles.add(ParagraphStyle(
        name="LectlySummary",
        fontName="Helvetica",
        fontSize=10,
        leading=16,
        textColor=LIGHT_GRAY,
        spaceAfter=16,
        alignment=TA_JUSTIFY,
    ))

    # Section heading
    styles.add(ParagraphStyle(
        name="SectionHeading",
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=20,
        textColor=PURPLE,
        spaceBefore=20,
        spaceAfter=8,
    ))

    # Body text
    styles.add(ParagraphStyle(
        name="BodyText2",
        fontName="Helvetica",
        fontSize=10,
        leading=16,
        textColor=HexColor("#2C2A25"),
        spaceAfter=8,
        alignment=TA_JUSTIFY,
    ))

    # Key point
    styles.add(ParagraphStyle(
        name="KeyPoint",
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=HexColor("#2C2A25"),
        leftIndent=16,
        spaceAfter=4,
    ))

    # Definition term
    styles.add(ParagraphStyle(
        name="DefTerm",
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=14,
        textColor=DARK_TEXT,
        leftIndent=16,
    ))

    # Definition body
    styles.add(ParagraphStyle(
        name="DefBody",
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=LIGHT_GRAY,
        leftIndent=16,
        spaceAfter=6,
    ))

    # Footer
    styles.add(ParagraphStyle(
        name="Footer",
        fontName="Helvetica",
        fontSize=8,
        textColor=MEDIUM_GRAY,
        alignment=TA_CENTER,
    ))

    # Label (small caps style)
    styles.add(ParagraphStyle(
        name="Label",
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=12,
        textColor=PURPLE,
        spaceAfter=4,
    ))

    return styles


def _add_header_footer(canvas_obj, doc):
    """Add header line and footer to each page."""
    canvas_obj.saveState()

    width, height = A4

    # Header: thin purple line
    canvas_obj.setStrokeColor(PURPLE)
    canvas_obj.setLineWidth(2)
    canvas_obj.line(30, height - 40, width - 30, height - 40)

    # Header: "Lectly" brand
    canvas_obj.setFont("Helvetica-Bold", 9)
    canvas_obj.setFillColor(PURPLE)
    canvas_obj.drawString(30, height - 35, "Lectly")

    # Footer
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.setFillColor(MEDIUM_GRAY)
    canvas_obj.drawCentredString(
        width / 2,
        20,
        f"Generated by Lectly  |  Page {doc.page}",
    )

    canvas_obj.restoreState()


def generate_notes_pdf(lecture_id: str) -> bytes:
    """Generate a PDF of lecture notes and return as bytes."""
    lecture = db_get_lecture(lecture_id)

    if not lecture:
        raise ValueError(f"Lecture {lecture_id} not found")

    notes = lecture.get("notes")
    if not notes:
        raise ValueError("No notes available for this lecture.")

    styles = _get_styles()
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=50,
        bottomMargin=40,
        leftMargin=30,
        rightMargin=30,
    )

    story = []

    # ── Title ──
    title_text = notes.get("title", "Untitled Lecture")
    story.append(Spacer(1, 10))
    story.append(Paragraph(title_text, styles["LectlyTitle"]))

    # ── Metadata line ──
    subject = lecture.get("subject", "")
    duration = lecture.get("duration_seconds")
    meta_parts = []
    if subject:
        meta_parts.append(f"Subject: {subject}")
    if duration:
        mins = int(float(duration) // 60)
        meta_parts.append(f"Duration: {mins} min")
    created = lecture.get("created_at", "")
    if created:
        try:
            dt = datetime.fromisoformat(created)
            meta_parts.append(f"Date: {dt.strftime('%B %d, %Y')}")
        except (ValueError, TypeError):
            pass

    if meta_parts:
        meta_text = "  |  ".join(meta_parts)
        story.append(Paragraph(meta_text, styles["Label"]))
        story.append(Spacer(1, 8))

    # ── Summary ──
    summary = notes.get("summary", "")
    if summary:
        story.append(Paragraph(summary, styles["LectlySummary"]))

    # Divider
    story.append(HRFlowable(
        width="100%",
        thickness=0.5,
        color=GOLD_BORDER,
        spaceAfter=10,
    ))

    # ── Sections ──
    sections = notes.get("sections", [])
    for i, section in enumerate(sections):
        heading = section.get("heading", f"Section {i + 1}")
        content = section.get("content", "")
        key_points = section.get("key_points", [])
        definitions = section.get("definitions", [])
        source_type = section.get("source_type", "original")

        section_elements = []

        # Section heading with number
        section_elements.append(
            Paragraph(f"{i + 1}. {heading}", styles["SectionHeading"])
        )

        # Source type badge
        if source_type == "ai_enhanced":
            section_elements.append(
                Paragraph(
                    '<font color="#7C3AED" size="7">AI-ENHANCED</font>',
                    styles["Label"],
                )
            )

        # Content paragraphs
        if content:
            # Split into paragraphs and render each
            paragraphs = content.split("\n\n") if "\n\n" in content else [content]
            for para in paragraphs:
                para = para.strip()
                if para:
                    # Escape XML special characters
                    para = para.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    section_elements.append(Paragraph(para, styles["BodyText2"]))

        # Key points
        if key_points:
            section_elements.append(Spacer(1, 6))
            section_elements.append(Paragraph("KEY POINTS", styles["Label"]))
            for point in key_points:
                point = str(point).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                section_elements.append(
                    Paragraph(f"•  {point}", styles["KeyPoint"])
                )

        # Definitions
        if definitions:
            section_elements.append(Spacer(1, 6))
            section_elements.append(Paragraph("DEFINITIONS", styles["Label"]))
            for d in definitions:
                if isinstance(d, dict):
                    term = str(d.get("term", "")).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    defn = str(d.get("definition", "")).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    section_elements.append(Paragraph(term, styles["DefTerm"]))
                    section_elements.append(Paragraph(defn, styles["DefBody"]))

        # Section divider
        section_elements.append(Spacer(1, 6))
        section_elements.append(HRFlowable(
            width="100%",
            thickness=0.3,
            color=GOLD_BORDER,
            spaceAfter=4,
        ))

        # Try to keep section together, but allow breaking for long sections
        story.extend(section_elements)

    # ── Footer note ──
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "These notes were generated by Lectly - AI-powered lecture notes for students.",
        styles["Footer"],
    ))

    # Build the PDF
    doc.build(story, onFirstPage=_add_header_footer, onLaterPages=_add_header_footer)

    pdf_bytes = buffer.getvalue()
    buffer.close()

    print(f"[Lectly] Generated PDF for lecture {lecture_id}: {len(pdf_bytes)} bytes")
    return pdf_bytes
